### ISSUE TITLE
`onDone` calls `onStartListener`

### ISSUE THREAD

**Issue by sebastinto** [aiyu-ayaan/tts-engine#1]
See relevant line below:

https://github.com/aiyu-ayaan/tts-engine/blob/737817f968715f78f62f587163d68d484cb20e75/tts-engine/src/main/java/com/atech/tts_engine/tts/engine/TextToSpeechEngine.kt#L60

I believe this should be `onDonelistener?.invoke()`

**Comment by moisesaq** [comment]
Hey 👋🏽  @aiyu-ayaan
When will this be merged? 🙏🏽

**Comment by aiyu-ayaan** [comment]
@moisesaq  My bad !! 😢 
@sebastinto Yep i will correct it

**Comment by moisesaq** [comment]
Great! 
Thanks @aiyu-ayaan 👏🏽
